params ["_container", "_caller", "_actionId"];
[_container, ["Purchase TOOLBOX: $100", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_toolkit",100],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ADENSONIE: $2", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_adenosine",2],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ATRAGMX: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_ATragMX",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase FIELD DRESSING: $3", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_fieldDressing",3],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BLOOD .25L: $10", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_bloodIV_250",10],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BLOOD .5L: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_bloodIV_500",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BLOOD 1L: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_bloodIV",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CABLE TIE: $3", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_CableTie",3],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CELLPHONE: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_Cellphone",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase DAGR: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_DAGR",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase DEAD MAN'S SWITCH: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_DeadManSwitch",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase DEFUSAL KIT: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_DefusalKit",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ENTRENCHING TOOL: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_EntrenchingTool",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase EPINEPHRINE: $2", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_epinephrine",2],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase FORTIFY TOOL: $1", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_Fortify",1],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase FULTON MX-991: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_Flashlight_MX991",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HUNTIR MONITOR: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_HuntIR_monitor",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase IR STROBE: $3", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_IR_Strobe_Item",3],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase KESTREL 4500NV: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_Kestrel4500",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase KSF-1: $10", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_Flashlight_KSF1",10],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase M152 FIRING DEVICE: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_M26_Clacker",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MAP TOOLS: $3", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_MapTools",3],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MICRODAGR GPS: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_microDAGR",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MORPHINE: $2", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_morphine",2],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase PERSONAL AID KIT: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_personalAidKit",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase PLASMA .25L: $10", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_plasmaIV_250",10],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase PLASMA .5L: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_plasmaIV_500",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase PLASMA 1L: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_plasmaIV",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase RANGE CARD: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_RangeCard",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SALINE 1L: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_salineIV_250",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SPLINT: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_splint",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SPOTTING SCOPE: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_SpottingScope",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SSWT KIT: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_Tripod",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SURGICAL KIT: $35", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_surgicalKit",35],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase TOURNIQUET: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_tourniquet",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase WIRECUTTER: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_wirecutter",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ANTIVIRUS PILLS: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["RyanZombiesAntiVirusTemporary_Item",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ANTIVIRUS INJECTOR: $100", "Economy System\functions\FN_PurchaseItem.sqf", ["RyanZombiesAntiVirusCure_Item",100],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HEADLAMP: $1", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_HeadLampItem",1],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BAKED BEANS: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_beans",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BOX OF MATCHES: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_matches",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CAN OPENER: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_canOpener",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CANTEEN: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_canteen",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CANTEEN (CLEANED): $30", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_canteenPurified",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase FUEL CANISTER: $40", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_canisterFuel",40],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase GEIGER MULLER COUNTER: $50", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_Geiger",50],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase GUTTING KNIFE: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_guttingKnife",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HOSE: $15", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_hose",15],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase NOTEPAD: $2", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_notepad",2],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase TIRE: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_tire",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase WATER PURIFICATION TABLETS: $10", "Economy System\functions\FN_PurchaseItem.sqf", ["rvg_purificationTablets",10],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase GPS: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["ItemGPS",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ANOMALY DETECTOR: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["DSA_Detector",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];