params ["_container", "_caller", "_actionId"];
[_container, ["Purchase .45 MACHINE PISTOL: $300", "Economy System\functions\FN_PurchaseItem.sqf", ["DSA_MachinePistol45",300],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase 9MM MACHINE PISTOL: $250", "Economy System\functions\FN_PurchaseItem.sqf", ["DSA_MachinePistol9mm",250],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ALUMINUM PIPE: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["Pipe_aluminium",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase AX: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_axe",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BAT: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["Bat_Clear",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BAT SPIKED: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["Bat_Spike",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BRASS KNUCKLES: $10", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_BrassKnuckles",10],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase BRUSH AX: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_brush_axe",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CHIAPPA RHINO 60DS: $100", "Economy System\functions\FN_PurchaseItem.sqf", ["hgun_Pistol_heavy_02_F",100],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CRAFTED AX: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_craftedAxe",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CROWBAR: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["Crowbar",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CUSTOM CONVERT II: $100", "Economy System\functions\FN_PurchaseItem.sqf", ["hgun_ACPC2_F",100],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase FIRE AX: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["FireAxe",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase FNX-45 TACTICAL: $200", "Economy System\functions\FN_PurchaseItem.sqf", ["hgun_Pistol_heavy_01_F",200],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HAMMER: $50", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_survival_weapon_2",50],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HEINZ MACE: $25", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_survival_weapon_1",25],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ICE AX: $40", "Economy System\functions\FN_PurchaseItem.sqf", ["IceAxe",40],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase KATANA: $75", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_Katana",75],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase KERABIT: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["Weap_melee_knife",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase M3 KNIFE: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["Knife_m3",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MAKAROV PM: $80", "Economy System\functions\FN_PurchaseItem.sqf", ["rhs_weap_makarov_pm",80],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MP-443 GRACH: $125", "Economy System\functions\FN_PurchaseItem.sqf", ["rhs_weap_pya",125],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase P99: $125", "Economy System\functions\FN_PurchaseItem.sqf", ["hgun_P07_F",125],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase PIPE STYLED SWORD: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_pipeStyledSword",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase POLICE BAT: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["Police_Bat",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ROD: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["Rod",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase RUSSIAN CAVALRY SWORD: $90", "Economy System\functions\FN_PurchaseItem.sqf", ["Sashka_Russian",90],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SAPPER SHOVEL: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["Shovel_Russian",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SMALL AX: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["Axe",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SMALL HAMMER: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_SmallHammer",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SPECTRUM DEVICE: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["hgun_esd_01_F",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SPIKED CLUB: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_ww1_Club",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase TAURUS JUDGE: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["hgun_Pistol_Signal_F",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase UNSC KNIFE: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["UNSC_Knife",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase VMH3: $5", "Economy System\functions\FN_PurchaseItem.sqf", ["ACE_VMH3",5],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase WW2 GERMAN KNIFE: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_survival_weapon_4",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase WW2 RUSSIAN KNIFE: $20", "Economy System\functions\FN_PurchaseItem.sqf", ["WBK_survival_weapon_3",20],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];