params ["_unit"];

private _arrayReturn = LB_fnc_arrayReturn;
private _convertWeightedArray = missionNamespace getVariable "FN_convertWeightedArray";

// Weighted arrays setup
headgearArraySelectionBB = [["headgearBB"] call _arrayReturn] call _convertWeightedArray;
headgearArraySelectionDT = [["headgearDT"] call _arrayReturn] call _convertWeightedArray;
facewearArraySelectionDT = [["facewearDT"] call _arrayReturn] call _convertWeightedArray;
headgearArraySelectionNH = [["headgearNH"] call _arrayReturn] call _convertWeightedArray;
headgearArraySelectionPF = [["headgearPF"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionPF = [["uniformPF"] call _arrayReturn] call _convertWeightedArray;
facewearArraySelectionRC = [["facewearRC"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionRC = [["uniformRC"] call _arrayReturn] call _convertWeightedArray;
facewearArraySelectionTRB = [["facewearTRB"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionTRB = [["uniformTRB"] call _arrayReturn] call _convertWeightedArray;
headgearArraySelectionUS = [["headgearUS"] call _arrayReturn] call _convertWeightedArray;
facewearArraySelectionUS = [["facewearUS"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionUS = [["uniformUS"] call _arrayReturn] call _convertWeightedArray;
headgearArraySelectionRU = [["headgearRU"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionRU = [["uniformRU"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionROA = [["uniformROA"] call _arrayReturn] call _convertWeightedArray;
headgearArraySelectionROA = [["headgearROA"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionPMC = [["uniformPMC"] call _arrayReturn] call _convertWeightedArray;
facewearArraySelectionPMC = [["facewearPMC"] call _arrayReturn] call _convertWeightedArray;
headgearArraySelectionWO = [["headgearWO"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionWO = [["uniformWO"] call _arrayReturn] call _convertWeightedArray;
uniformArraySelectionALF = [["uniformALF"] call _arrayReturn] call _convertWeightedArray;
facewearArraySelectionALF = [["facewearALF"] call _arrayReturn] call _convertWeightedArray;
facewearArraySelectionBandit = [["facewearBandit"] call _arrayReturn] call _convertWeightedArray;

private _sanity = _unit getVariable ["sanityLevel", 100];
if (!(_unit getVariable ["Renegade_Relation", false])) then {
    if (_sanity > 10) then {
        private _playerUniform = uniform _unit;
        private _playerHeadgear = headgear _unit;
        private _playerGoggles = goggles _unit;
        switch true do {
            case (_playerHeadgear in headgearArraySelectionBB): {
                _unit setVariable ["SU_Relation",true,true];
                _unit setVariable ["BB_Relation",true,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerHeadgear in headgearArraySelectionDT && _playerGoggles in facewearArraySelectionDT): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",true,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",true,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerHeadgear in headgearArraySelectionNH): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",true,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",true,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerHeadgear in headgearArraySelectionPF && _playerUniform in uniformArraySelectionPF): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",true,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerGoggles in facewearArraySelectionRC && _playerUniform in uniformArraySelectionRC): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",true,true];
                _unit setVariable ["RC_Relation",true,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerUniform in uniformArraySelectionTRB && _playerGoggles in facewearArraySelectionTRB): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",true,true];
                _unit setVariable ["RC_Relation",true,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerHeadgear in headgearArraySelectionUS && _playerUniform in uniformArraySelectionUS && _playerGoggles in facewearArraySelectionUS): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",true,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerHeadgear in headgearArraySelectionRU && _playerUniform in uniformArraySelectionRU): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",true,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerHeadgear in headgearArraySelectionROA && _playerUniform in uniformArraySelectionROA): {
                _unit setVariable ["SU_Relation",true,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",true,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerUniform in uniformArraySelectionPMC && _playerGoggles in facewearArraySelectionPMC): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",true,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerHeadgear in headgearArraySelectionWO && _playerUniform in uniformArraySelectionWO): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",true,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerUniform in uniformArraySelectionALF && _playerGoggles in facewearArraySelectionALF): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",true,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            case (_playerGoggles in facewearArraySelectionBandit): {
                _unit setVariable ["SU_Relation",false,true];
                _unit setVariable ["BB_Relation",false,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",true,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
            default {
                _unit setVariable ["SU_Relation",true,true];
                _unit setVariable ["BB_Relation",true,true];
                _unit setVariable ["PF_Relation",false,true];
                _unit setVariable ["ALF_Relation",false,true];
                _unit setVariable ["WO_Relation",false,true];
                _unit setVariable ["RU_Relation",false,true];
                _unit setVariable ["US_Relation",false,true];
                _unit setVariable ["NH_Relation",false,true];
                _unit setVariable ["TRB_Relation",false,true];
                _unit setVariable ["RC_Relation",false,true];
                _unit setVariable ["DT_Relation",false,true];
                _unit setVariable ["ROA_Relation",false,true];
                _unit setVariable ["PMC_Relation",false,true];
                _unit setVariable ["Bandit_Relation",false,true];
                _unit setVariable ["Renegade_Relation",false,true];
            };
        };
    } else {
        _unit setVariable ["SU_Relation",false,true];
        _unit setVariable ["BB_Relation",false,true];
        _unit setVariable ["PF_Relation",true,true];
        _unit setVariable ["ALF_Relation",false,true];
        _unit setVariable ["WO_Relation",false,true];
        _unit setVariable ["RU_Relation",false,true];
        _unit setVariable ["US_Relation",false,true];
        _unit setVariable ["NH_Relation",false,true];
        _unit setVariable ["TRB_Relation",false,true];
        _unit setVariable ["RC_Relation",false,true];
        _unit setVariable ["DT_Relation",false,true];
        _unit setVariable ["ROA_Relation",false,true];
        _unit setVariable ["PMC_Relation",false,true];
        _unit setVariable ["Bandit_Relation",false,true];
    };
};