/*
    LB_Conversations.sqf
    --------------------
    Returns a HashMap with two keys:
      - "ambient": HashMap<faction -> array of conversations>
      - "combat" : HashMap<faction -> array of short combat lines>

    Factions:
      Use whatever keys you prefer. If you set group variable "LB_faction", the
      system will use that. Otherwise it falls back to engine faction (e.g., "BLU_F").
      A "*" entry acts as a fallback when a faction key isn't present.

    Conversation format:
      A conversation is an ARRAY of "entries".
      Each entry = [ROLE, TEXT, MIN_DELAY, MAX_DELAY]
        ROLE: "LEADER" or "RANDOM" (random non-leader from the same group; falls back to leader)
        TEXT: String the AI will say (globalChat)
        MIN_DELAY / MAX_DELAY: seconds to wait *after* saying this line before the next line.
                               Use 0,0 for no pause. The system will pick a random value in [min, max].

    Examples below are placeholders; replace with your content.


private _ambient = createHashMapFromArray [
    // US-like (rename to your custom key e.g. "US" if you use LB_faction)
    ["US", [
        [
            ["LEADER", "Keep your intervals.", 0.0, 0.0],
            ["RANDOM", "Copy, holding spacing.", 1.2, 2.0],
            ["LEADER", "Eyes open for survivors.", 1.0, 1.6]
        ],
        [
            ["LEADER", "Anyone see movement?", 0.0, 0.0],
            ["RANDOM", "Negative. Quiet out there.", 1.0, 1.8]
        ]
    ]],

    // RU-like
    ["RU", [
        [
            ["LEADER", "Spokoĭno. Dvizhemsya dalshe.", 0.0, 0.0],
            ["RANDOM", "Ponial. Derzhim stroy.", 1.0, 1.6]
        ]
    ]],

	//New Horizon
	["NH", [
        [
            ["LEADER", "You see that the Boonie Boys are back in town?", 0.0, 0.0],
            ["RANDOM", "Yeah, I heard their leader comeback for some artifact.", 2, 3],
            ["LEADER", "What a bunch of fools, but I can't blame them for being brave.", 2, 3],
            ["RANDOM", "True, if they weren't a bunch of weirdo's, I'd respect them a bit more.", 2, 3]
        ],
        [
            ["LEADER", "Have you been catching up on your greek mythos recently Bob?", 0.0, 0.0],
            ["RANDOM", "Why the fuck would I do that?", 2, 3],
            ["LEADER", "Deadman's Trident loves asking about that stuff. Ya know they actually believe in Thor and what not.", 3, 4],
            ["RANDOM", "That's Norse mythology you fucking idiot, and no I haven't been reading on Greek stuff.", 2, 3],
            ["LEADER", "Why not? We are technically allied with them.", 2, 3],
            ["RANDOM", "Because, their faction is on it's last ropes. They keep going out on these 'pilgrimages' to dangerous parts of the island. Most of their members don't even know Greek mythos anymore because of it.", 5, 6],
            ["LEADER", "What a bunch of fools", 2, 3]
        ]
    ]],

    // Fallback conversations (used if faction key not present)
    ["*", [
        [
            ["LEADER", "All quiet.", 0.0, 0.0],
            ["RANDOM", "Let’s hope it stays that way.", 1.0, 1.6]
        ]
    ]]
];

private _combat = createHashMapFromArray [
    ["US", ["Bandit 7, this is Bandit 6, we've got multiple Sierra's in the area over",
        "Bandit 6, this is Bandit 1-10, moving to engage over",
        "Bandit 2, requesting gun run on my position over",
        "Bandit 3, requesting 9-line over",
        "Line 1: Pickup location - grid sector Whiskey Papa, break",
        "Line 2: Radio freq 1 / call sign - Bandit 1-12, Bandit 3, break",
        "Line 3: Patients by precedence - 1 urgent, 2 priority, break",
        "Line 4: Special equipment - none, break",
        "Line 5: Patients by type - 2 litter, 1 ambulatory, break",
        "Line 6: Security at pickup - enemy in vicinity; approach from south, break",
        "Line 7: Marking - green smoke; IR strobe at night, break",
        "Line 8: Nationality / status - 3 Bandits, break",
        "Line 9: Terrain / hazards - open field, firm LZ; negative CBRN, over",
        "Bandit 7, this is Bandit 6, contact front, squad-size at sector Oscar Yankee, over",
        "Bandit 6, this is Bandit 1-10, moving to engage, ETA two mikes, over",
        "Bandit 2, this is Bandit 6, request CAS Type 1 on my mark, danger close, over",
        "Bandit 7, be advised, Objective Bravo not secure, do not approach, over",
        "Bandit 6, say again last transmission, you were broken and unreadable, over",
        "Bandit 1-7, shift fires north five-zero meters, friendlies moving, over",
        "Bandit 2, push to Phase Line Red and hold short, acknowledge, over",
        "Bandit 6, this is Bandit 1-11, Oscar Mike to the LZ, LZ cold, over",
        "Bandit 7, request SITREP, how copy, over",
        "Bandit 1-10, set overwatch on Building Two, report set, over",
        "Bandit 6, negative contact along Route Copper, continuing movement, over",
        "Bandit 3, check fire, friendlies danger close at azimuth 090, over",
        "Bandit 7, solid copy, adjusting axis of advance to 270, over",
        "Bandit 2, confirm PID, then engage by fire, over",
        "Bandit Actual, this is Bandit 1-6, ammo yellow, casualties yellow, continue mission, over",
        "Bandit 6, stand by for grid, break, grid sector golf hotel, mortar point of origin, over",
        "Bandit 3, request route clearance to Checkpoint Delta, over",
        "Bandit 6, roger, switch to four-zero point zero zero for fires, report when up, over"
    ]],
    ["RU", ["«Альфа», это «Альфа-1-6», контакт спереди, двести метров, открываем огонь, приём",
        "«Альфа», «Альфа-1-6» на связи, требуются подкрепления и боеприпасы, приём",
        "«Альфа-1-10», «1-11», «1-12», работайте по указанной цели, приём",
        "«Альфа-1-10», запрашиваю санэвак: один тяжёлый, один лёгкий, приём",
        "«Альфа-3», запрашиваю авиаудар по квадрату 042 087, свой маркер — красный дым, приём",
        "«Альфа-3», разрешите огонь на поражение, приём",
        "«Альфа-1-7», «Альфа-1-10», обойдите слева и займите фланг, приём",
        "«Альфа», это «Альфа-1-2», ведём бой, прошу разрешение на штурм, приём",
        "«Альфа», к сведению: задача «Браво» выполнена, организуем охранение, приём",
        "«Альфа-1-10», выдвигайтесь на рубеж «Красный» и удерживайте позицию, приём",
        "«Альфа-1-7», подавляю второе здание, отмечаю дымом, приём",
        "«Альфа-3», выдвигаемся к LZ, прибытие через две минуты, приём",
        "«Альфа-1-6», состояние зелёное, боекомплект жёлтый, продолжаем выполнение, приём",
        "«Альфа-1-11», прекратить огонь, свои рядом, ждите указаний, приём",
        "«Альфа», это «Альфа-1-7», по нам точный огонь, требуется дым и отход влево, приём",
        "«Альфа-1-10», займите позицию наблюдения по сетке 042 087, доложите «в позиции», приём",
        "«Альфа», принято, смещаю огонь на север пятьдесят метров, так точно, приём",
        "«Альфа-1-6», требуется «девятка» по раненому, готов к передаче, приём",
        "«Альфа», проверка связи, как слышите «один-шесть», приём",
        "«Альфа-1-10», контроль сектора восток, возможна техника противника, приём"
    ]],
    ["ROA", ["Άλφα actual, εδώ Άλφα 1-6, έχουμε εμπλακεί με τον εχθρό, τέλος",
        "Άλφα actual, εδώ Άλφα 1-6, ζητώ ενισχύσεις, τέλος... Θετικό, τέλος",
        "Άλφα 1-10, 1-11, 1-12, προσβάλτε εκείνον τον στόχο, τέλος",
        "Άλφα 1-10, ζητώ 9-line, τέλος",
        "Άλφα 3 actual, ζητώ πέρασμα με πυροβόλο, τέλος... Θετικό, τέλος",
        "Άλφα 3 actual, ζητώ άδεια για θανατηφόρα πυρά, τέλος",
        "Άλφα 1-10, εδώ Άλφα 1-7, παράκαμψε αριστερά με την ομάδα σου, τέλος",
        "Άλφα actual, εδώ Άλφα 1-2, επαφή μπροστά, 200 μέτρα, ζητώ άδεια προσβολής, τέλος",
        "Άλφα actual, προς ενημέρωση, ο στόχος Μπράβο επετεύχθη, στήνουμε ασφάλεια, τέλος",
        "Άλφα 1-10, προωθηθείτε στη γραμμή φάσης Κόκκινο και κρατήστε θέση, τέλος",
        "Άλφα 1-7, κατασταλτικά πυρά στο κτίριο δύο, σημειώνω με καπνό, τέλος",
        "Άλφα 3 actual, είμαστε Όσκαρ Μάικ προς τη Ζώνη Προσγείωσης (LZ), ETA δύο λεπτά, τέλος",
        "Άλφα 1-6, κατάσταση πράσινη, πυρομαχικά κίτρινα, συνεχίζουμε την αποστολή, τέλος",
        "Άλφα 1-11, παύση πυρών, φίλιοι πολύ κοντά, αναμείνατε, τέλος",
        "Άλφα actual, εδώ Άλφα 1-7, δεχόμαστε εύστοχα πυρά, ζητώ καπνό και άλματα αριστερά, τέλος",
        "Άλφα 1-10, λάβετε θέση επιτήρησης στον κάνναβο 042 087, αναφέρατε «σε θέση», τέλος",
        "Άλφα actual, έλαβα το τελευταίο, μετατοπίζω τα πυρά 50 μέτρα βόρεια... Θετικό, τέλος"
    ]],
    ["PMC", ["Alpha actual, this is Alpha 1-6, we have engaged the enemy over",
        "Alpha actual, this is Alpha 1-6, requesting backup over... Affirmative over",
        "Alpha 1-10, 1-11, 1-12, engage that target over",
        "Alpha 1-10, requesting 9-line over",
        "Alpha 3 actual, requesting gun run over... Affirmative over",
        "Alpha 3 actual requesting permission to shoot to kill over",
        "Alpha 1-10, this is Alpha 1-7, flank left with your team over",
        "Alpha actual, this is Alpha 1-2, contact front, 200 meters, request permission to engage over",
        "Alpha actual, be advised, objective Bravo reached, setting security over",
        "Alpha 1-10, push to phase line Red and hold short over",
        "Alpha 1-7, suppressing fire on building two, marking with smoke over",
        "Alpha 3 actual, we are Oscar Mike to the LZ, ETA two mikes over",
        "Alpha 1-6, status green, ammo yellow, continuing mission over",
        "Alpha 1-11, check fire, friendlies danger close, wait one over",
        "Alpha actual, this is Alpha 1-7, taking accurate fire, request smoke and bound left over",
        "Alpha 1-10, set overwatch on grid 019 087, call set over",
        "Alpha actual, copy last, shifting fires north 50 meters... Affirmative over"
    ]],
    ["SU", ["We got strays!",
        "They're not in the Union, engage!",
        "Bandits here? No way man...",
        "We've got a rat here dammit!",
        "Open fire, they aren't friendly!",
        "Union fighters, assemble!",
        "Where the heck is our backup!?",
        "Boonie Boys is supposed to be backing us up, where the heck are they?",
        "They won't know what hit them the rapscallions!",
        "Let's finish this quick, my filter is almost gone!",
        "Good shot Terrance, just the way they teach at Unions academy!",
        "Shoot them, just like the way they taught us at the academy!",
        "CONTACT!",
        "Raiders located!",
        "Union fighters, attack!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!",
        "Contact, engage Unioners!"
    ]],
    ["RC", ["Shit, we've got hostiles!",
        "I thought Raven 2 said this area was clear?!",
        "All Ravens, move to engage!",
        "I'm not being paid enough for this...",
        "Your time has come!",
        "What made you delusional enough to fight the Raven's!",
        "All that'll be left of you is your shadow when we're through with you!",
        "Contact, Raven's to arms!",
        "Raven 3-6, this is Raven 3-3, we have contact in the Charlie sector",
        "Sector not clear, I say again, sector not clear!",
        "Tell Raven 10-8 to pull out from sector Yankee, we need backup!",
        "Raven 1-6, this is Raven 3-6, requesting medevac... Denied?! The fuck you mean denied?!",
        "Time to die in obscurity mother fucker!",
        "Raven actual, engage all targets!",
        "Raven 2-100, engage all targets!",
        "Raven 2-110, engage all targets!",
        "Raven 2-111, engage all targets!",
        "Raven 2-112, engage all targets!",
        "Raven 2-113, engage all targets!",
        "Raven 2-114, engage all targets!",
        "Raven 2-115, engage all targets!",
        "Raven 2-116, engage all targets!",
        "Raven 2-117, engage all targets!",
        "Raven 2-118, engage all targets!",
        "Raven 2-119, engage all targets!",
        "Raven 2-120, engage all targets!",
        "Raven 2-121, engage all targets!",
        "Raven 2-122, engage all targets!"
    ]],
    ["TRB", ["Сдохните, капитулы!",
        "Капиталистическая сволочь!",
        "У нас есть связь!",
        "Вызовите подкрепление!",
        "Красная Пуля не отступит!",
        "За матушку Россию!",
        "Мне просто нужно было присоединиться к Медведю...",
        "Мне просто нужно было присоединиться к группе Вагнера...",
        "Контакт контакт контакт!",
        "Убейте их всех!",
        "убей убей убей!"
    ]],
    ["WO", ["Töte sie!",
        "Für die neue Weltordnung!",
        "Skalp sie!",
        "Kontakt Kontakt Kontakt!",
        "Glauben die Idioten, sie könnten es mit uns aufnehmen?",
        "Dann zu Tode!",
        "Wenn sie nicht für uns sind, sind sie gegen uns!",
        "Erschießt sie für unseren Anführer!",
        "Für Hans!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!",
        "Für die neue Welt!"
    ]],
    ["ALF", ["Leave this island at once!",
        "Altis deserves better!",
        "Bandits like you don't deserve to live on this island!",
        "We've got contacts!",
        "Single file! Single file!",
        "Liberator 6, requesting backup!",
        "Liberator, bound to my position!",
        "These fools have no idea who they're messing with...",
        "Trash like you don't deserve to live!",
        "Damn tourists!",
        "Contact contact contact!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!",
        "For Altis!"
    ]],
    ["PF", ["You look like delicious!",
        "Time for a feast!",
        "Steak's back on the menu boys!",
        "Your head will look great on a pike!",
        "I think this one will look good seared!",
        "I'm going to feed you your own guts mother fucker!",
        "I hope Owen dies in this engagement, he has some nice thighs that'll go great with my tac bacon.",
        "AAHHHHHHHHHHHHHHH DIE ALREADY",
        "Shank em' Paul!",
        "DIE DIE DIE",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!",
        "No survivors!"
    ]],
    ["Bandit", ["Kill em' and take their shit!",
        "Rob em!",
        "Prank em' John!",
        "I should've joined the Boonie Boys...",
        "Where is all our guys? The damn deserters...",
        "Man, I only wanted to do some robbin' now I'm going to die...",
        "First George, now Randy, how many more have to die...",
        "We've got assholes to kill!",
        "Once their dead, let's sell their corpses to Pigs Flesh. I heard their offering good deals for fresh ones.",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!",
        "Time to die!"
    ]],
    ["BB", ["Terry, look alive, we've got contact!",
        "Bob, put down the shovel and shoot them!",
        "Light em' up!",
        "I should've joined the New Horizion...",
        "Where the hell is our backup!",
        "Kill the bastards!",
        "What are you doing Jerry? We've got contact!",
        "Where the hell are the Boonie Boy SF, we're going to need them...",
        "Why the hell did I even sign up for this...",
        "Shoot them until they stop moving!",
        "As long as we don't fight the skulls, I'll be good.",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!",
        "Give em' hell!"
    ]],
    ["DT", ["Για τον Δία!",
        "Για τον Άρη!",
        "Για τους θεούς!",
        "είναι παντού!",
        "Μα τους θεούς, θα πεθάνεις σήμερα!",
        "Πού στο καλό είναι ο Νέος Ορίζοντας",
        "Επικοινωνία, ακριβώς μπροστά!",
        "Για τον Ποσειδώνα!",
        "σκοτώστε τον άθεο!"
    ]],
	["NH", ["Get up idiot, we got hostiles!", 
        "Shit, there's more than I thought!", 
        "I should've joined the Boonie Boys...",
        "Die you mother fuckers!",
        "Don't worry guys, these idiots are weak",
        "Kill them quick, I want to go mutant hunting later.",
        "Where the fuck did he go?",
        "Die you idiots!",
        "Woah, shots fired!",
        "Where the hell is Deadman's, they were suppoed to back us up...", 
        "Only the strong will survive!",
        "Only idiots would attack us!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!",
        "Kill those fools!"
    ]],
    ["*",   ["Taking fire!", "Return fire!"]]
];

createHashMapFromArray [
    ["ambient", _ambient],
    ["combat",  _combat]
];